<a href="https://colab.research.google.com/github/rahmattamim/belajarPython/blob/main/machine_learning_kelompok_2_tugas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#SKALAR : Bilangan tunggal
a = 4
b = 8
c = a + b
print(a, b, c)

4 8 12


In [ ]:
#VEKTOR : Kumpulan skalar
#import library numpy
import numpy as np
a = np.array([2, 4, 8])
b = np.array([1, 3, 5])

#PENJUMLAHAN
c = a + b
print(a, b, c)

#pengurangan
d = a - b
print(a, b, d)

#perkalian
e = a*b
print(a, b, e)

#pembagian
f = a/b
print(a, b, f)

#ekspresi dot
g = np.dot(a, b)
print(a, b, g)



[2 4 8] [1 3 5] [ 3  7 13]
[2 4 8] [1 3 5] [1 1 3]
[2 4 8] [1 3 5] [ 2 12 40]
[2 4 8] [1 3 5] [2.         1.33333333 1.6       ]
[2 4 8] [1 3 5] 54


In [ ]:
#Matriks : Kumpulan vektor
import numpy as np
matriks = np.array([c, d, e, f])
print(matriks)



[[ 3.          7.         13.        ]
 [ 1.          1.          3.        ]
 [ 2.         12.         40.        ]
 [ 2.          1.33333333  1.6       ]]


In [ ]:
#menghitung nilai determinan (untuk ordo baris dalam dan kolom sama atau matrix persegi)
a = np.array([[1, 2], [3, 4]])
determinan = np.linalg.det(a)
print(determinan)

-2.0000000000000004


In [ ]:
#transpose => merubah kolom menjadi baris
a = np.array([[1, 2, 3], [4, 5, 6]])
transpose = np.transpose(a)
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#mencari invers matriks a
a = np.array([[1, 2], [3, 4]])
invers = np.linalg.inv(a)
print(invers)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
import numpy as np
!pip install torch # install torch if you haven't already
import torch # import the torch module

array_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor_numpy = torch.from_numpy(array_numpy)
print("\nTensor dari NumPy Array:\n", tensor_numpy)


Tensor dari NumPy Array:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
